spring:
  application:
    name: hotel-availability

  data:
    mongodb:
      host: localhost
      port: 27017
      database: hotel-availability-db

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: hotel-availability-group
      auto-offset-reset: earliest
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    listener:
      missing-topics-fatal: false


server:
  port: 8080

logging:
  level:
    root: INFO

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
